# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vehiclecontroller/vehiclecontroller.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='vehiclecontroller/vehiclecontroller.proto',
  package='vehiclecontroller',
  syntax='proto3',
  serialized_options=_b('\n\"io.grpc.examples.vehiclecontrollerB\021VehicleControllerP\001\242\002\003HLW'),
  serialized_pb=_b('\n)vehiclecontroller/vehiclecontroller.proto\x12\x11vehiclecontroller\"-\n\x0c\x44riveRequest\x12\x0e\n\x06torque\x18\x01 \x01(\x02\x12\r\n\x05\x61ngle\x18\x02 \x01(\x02\" \n\rDriveResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\x61\n\x11VehicleController\x12L\n\x05\x44rive\x12\x1f.vehiclecontroller.DriveRequest\x1a .vehiclecontroller.DriveResponse\"\x00\x42?\n\"io.grpc.examples.vehiclecontrollerB\x11VehicleControllerP\x01\xa2\x02\x03HLWb\x06proto3')
)




_DRIVEREQUEST = _descriptor.Descriptor(
  name='DriveRequest',
  full_name='vehiclecontroller.DriveRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='torque', full_name='vehiclecontroller.DriveRequest.torque', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='angle', full_name='vehiclecontroller.DriveRequest.angle', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=64,
  serialized_end=109,
)


_DRIVERESPONSE = _descriptor.Descriptor(
  name='DriveResponse',
  full_name='vehiclecontroller.DriveResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='vehiclecontroller.DriveResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=111,
  serialized_end=143,
)

DESCRIPTOR.message_types_by_name['DriveRequest'] = _DRIVEREQUEST
DESCRIPTOR.message_types_by_name['DriveResponse'] = _DRIVERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DriveRequest = _reflection.GeneratedProtocolMessageType('DriveRequest', (_message.Message,), {
  'DESCRIPTOR' : _DRIVEREQUEST,
  '__module__' : 'vehiclecontroller.vehiclecontroller_pb2'
  # @@protoc_insertion_point(class_scope:vehiclecontroller.DriveRequest)
  })
_sym_db.RegisterMessage(DriveRequest)

DriveResponse = _reflection.GeneratedProtocolMessageType('DriveResponse', (_message.Message,), {
  'DESCRIPTOR' : _DRIVERESPONSE,
  '__module__' : 'vehiclecontroller.vehiclecontroller_pb2'
  # @@protoc_insertion_point(class_scope:vehiclecontroller.DriveResponse)
  })
_sym_db.RegisterMessage(DriveResponse)


DESCRIPTOR._options = None

_VEHICLECONTROLLER = _descriptor.ServiceDescriptor(
  name='VehicleController',
  full_name='vehiclecontroller.VehicleController',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=145,
  serialized_end=242,
  methods=[
  _descriptor.MethodDescriptor(
    name='Drive',
    full_name='vehiclecontroller.VehicleController.Drive',
    index=0,
    containing_service=None,
    input_type=_DRIVEREQUEST,
    output_type=_DRIVERESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_VEHICLECONTROLLER)

DESCRIPTOR.services_by_name['VehicleController'] = _VEHICLECONTROLLER

# @@protoc_insertion_point(module_scope)
