// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: vehiclecontroller/vehiclecontroller.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Vehiclecontroller {

  /// <summary>Holder for reflection information generated from vehiclecontroller/vehiclecontroller.proto</summary>
  public static partial class VehiclecontrollerReflection {

    #region Descriptor
    /// <summary>File descriptor for vehiclecontroller/vehiclecontroller.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static VehiclecontrollerReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cil2ZWhpY2xlY29udHJvbGxlci92ZWhpY2xlY29udHJvbGxlci5wcm90bxIR",
            "dmVoaWNsZWNvbnRyb2xsZXIiQgoMRHJpdmVSZXF1ZXN0Eg4KBnRvcnF1ZRgB",
            "IAEoAhINCgVhbmdsZRgCIAEoAhITCgticmFrZVRvcnF1ZRgDIAEoAiIgCg1E",
            "cml2ZVJlc3BvbnNlEg8KB3N1Y2Nlc3MYASABKAgypwMKEVZlaGljbGVDb250",
            "cm9sbGVyElMKDERyaXZlRm9yd2FyZBIfLnZlaGljbGVjb250cm9sbGVyLkRy",
            "aXZlUmVxdWVzdBogLnZlaGljbGVjb250cm9sbGVyLkRyaXZlUmVzcG9uc2Ui",
            "ABJUCg1Ecml2ZUJhY2t3YXJkEh8udmVoaWNsZWNvbnRyb2xsZXIuRHJpdmVS",
            "ZXF1ZXN0GiAudmVoaWNsZWNvbnRyb2xsZXIuRHJpdmVSZXNwb25zZSIAEkwK",
            "BVN0ZWVyEh8udmVoaWNsZWNvbnRyb2xsZXIuRHJpdmVSZXF1ZXN0GiAudmVo",
            "aWNsZWNvbnRyb2xsZXIuRHJpdmVSZXNwb25zZSIAEksKBElkbGUSHy52ZWhp",
            "Y2xlY29udHJvbGxlci5Ecml2ZVJlcXVlc3QaIC52ZWhpY2xlY29udHJvbGxl",
            "ci5Ecml2ZVJlc3BvbnNlIgASTAoFQnJha2USHy52ZWhpY2xlY29udHJvbGxl",
            "ci5Ecml2ZVJlcXVlc3QaIC52ZWhpY2xlY29udHJvbGxlci5Ecml2ZVJlc3Bv",
            "bnNlIgBCPwoiaW8uZ3JwYy5leGFtcGxlcy52ZWhpY2xlY29udHJvbGxlckIR",
            "VmVoaWNsZUNvbnRyb2xsZXJQAaICA0hMV2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Vehiclecontroller.DriveRequest), global::Vehiclecontroller.DriveRequest.Parser, new[]{ "Torque", "Angle", "BrakeTorque" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Vehiclecontroller.DriveResponse), global::Vehiclecontroller.DriveResponse.Parser, new[]{ "Success" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class DriveRequest : pb::IMessage<DriveRequest> {
    private static readonly pb::MessageParser<DriveRequest> _parser = new pb::MessageParser<DriveRequest>(() => new DriveRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<DriveRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Vehiclecontroller.VehiclecontrollerReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DriveRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DriveRequest(DriveRequest other) : this() {
      torque_ = other.torque_;
      angle_ = other.angle_;
      brakeTorque_ = other.brakeTorque_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DriveRequest Clone() {
      return new DriveRequest(this);
    }

    /// <summary>Field number for the "torque" field.</summary>
    public const int TorqueFieldNumber = 1;
    private float torque_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float Torque {
      get { return torque_; }
      set {
        torque_ = value;
      }
    }

    /// <summary>Field number for the "angle" field.</summary>
    public const int AngleFieldNumber = 2;
    private float angle_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float Angle {
      get { return angle_; }
      set {
        angle_ = value;
      }
    }

    /// <summary>Field number for the "brakeTorque" field.</summary>
    public const int BrakeTorqueFieldNumber = 3;
    private float brakeTorque_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float BrakeTorque {
      get { return brakeTorque_; }
      set {
        brakeTorque_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as DriveRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(DriveRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Torque, other.Torque)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Angle, other.Angle)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(BrakeTorque, other.BrakeTorque)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Torque != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Torque);
      if (Angle != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Angle);
      if (BrakeTorque != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(BrakeTorque);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Torque != 0F) {
        output.WriteRawTag(13);
        output.WriteFloat(Torque);
      }
      if (Angle != 0F) {
        output.WriteRawTag(21);
        output.WriteFloat(Angle);
      }
      if (BrakeTorque != 0F) {
        output.WriteRawTag(29);
        output.WriteFloat(BrakeTorque);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Torque != 0F) {
        size += 1 + 4;
      }
      if (Angle != 0F) {
        size += 1 + 4;
      }
      if (BrakeTorque != 0F) {
        size += 1 + 4;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(DriveRequest other) {
      if (other == null) {
        return;
      }
      if (other.Torque != 0F) {
        Torque = other.Torque;
      }
      if (other.Angle != 0F) {
        Angle = other.Angle;
      }
      if (other.BrakeTorque != 0F) {
        BrakeTorque = other.BrakeTorque;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 13: {
            Torque = input.ReadFloat();
            break;
          }
          case 21: {
            Angle = input.ReadFloat();
            break;
          }
          case 29: {
            BrakeTorque = input.ReadFloat();
            break;
          }
        }
      }
    }

  }

  public sealed partial class DriveResponse : pb::IMessage<DriveResponse> {
    private static readonly pb::MessageParser<DriveResponse> _parser = new pb::MessageParser<DriveResponse>(() => new DriveResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<DriveResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Vehiclecontroller.VehiclecontrollerReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DriveResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DriveResponse(DriveResponse other) : this() {
      success_ = other.success_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DriveResponse Clone() {
      return new DriveResponse(this);
    }

    /// <summary>Field number for the "success" field.</summary>
    public const int SuccessFieldNumber = 1;
    private bool success_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Success {
      get { return success_; }
      set {
        success_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as DriveResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(DriveResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Success != other.Success) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Success != false) hash ^= Success.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Success != false) {
        output.WriteRawTag(8);
        output.WriteBool(Success);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Success != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(DriveResponse other) {
      if (other == null) {
        return;
      }
      if (other.Success != false) {
        Success = other.Success;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Success = input.ReadBool();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
